name: 'Build and Push Docker Image'
description: 'Кастомное action для сборки и пуша Docker-образов'

inputs:
  appName:
    description: 'Имя приложения'
    required: true
  appContexPath:
    description: 'Путь к Docker-контексту'
    required: true
  registry:
    description: 'Регистр Docker'
    required: true
  username:
    description: 'Имя пользователя для Docker'
    required: true
  password:
    description: 'Пароль для Docker'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.appContexPath }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.appName }}:latest
