name: Build and Push All

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build from'
        required: true
        default: 'main'

jobs:
  build-and-push-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        appName: ['petstoreapp', 'orderitemsreserver', 'petstoreorderservice', 'petstorepetservice', 'petstoreproductservice']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }} 
        
      - name: Build image ${{ matrix.appName }}
        uses: ./.github/actions/build-and-push-module
        with:
          appContexPath: './${{ matrix.appName }}'
          appName: ${{ matrix.appName }}
          registry: ${{ vars.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          tag: 'v1'
